"""empty message

Revision ID: 982e45225993
Revises: 
Create Date: 2020-07-15 18:15:41.205330

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '982e45225993'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('cliente',
    sa.Column('cedula', sa.Integer(), nullable=False),
    sa.Column('fechaIngreso', sa.DateTime(), nullable=True),
    sa.Column('fechaExpedicion', sa.DateTime(), nullable=True),
    sa.Column('ciudadExpedicion', sa.String(length=30), nullable=True),
    sa.Column('nombres', sa.String(length=255), nullable=True),
    sa.Column('apellidos', sa.String(length=255), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('municipioRucom', sa.String(length=45), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('huella', sa.String(length=255), nullable=True),
    sa.PrimaryKeyConstraint('cedula')
    )
    op.create_table('empleado',
    sa.Column('idEmpleado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('correo', sa.String(length=255), nullable=True),
    sa.Column('contrasenia', sa.String(length=40), nullable=True),
    sa.PrimaryKeyConstraint('idEmpleado')
    )
    op.create_table('empresa',
    sa.Column('nit', sa.String(length=80), nullable=False),
    sa.Column('direccion', sa.String(length=255), nullable=True),
    sa.Column('ciudad', sa.String(length=30), nullable=True),
    sa.Column('telefono', sa.String(length=30), nullable=True),
    sa.Column('representanteLegal', sa.String(length=255), nullable=True),
    sa.Column('rucom', sa.String(length=30), nullable=True),
    sa.Column('municipioRucom', sa.String(length=45), nullable=True),
    sa.Column('departamentoRucom', sa.String(length=45), nullable=True),
    sa.Column('logo', sa.String(length=255), nullable=True),
    sa.Column('cedulaRepresentante', sa.Integer(), nullable=True),
    sa.Column('cedulaLugaeExpedicion', sa.String(length=30), nullable=True),
    sa.Column('nombreEmpresaRucom', sa.String(length=45), nullable=True),
    sa.Column('emailEmpresa', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('nit')
    )
    op.create_table('compra',
    sa.Column('idCompra', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idEmpresa', sa.String(length=80), nullable=True),
    sa.Column('ley', sa.String(length=255), nullable=True),
    sa.Column('vrGramo', sa.String(length=30), nullable=True),
    sa.Column('nota', sa.String(length=300), nullable=True),
    sa.Column('estadoCompra', sa.String(length=40), nullable=True),
    sa.Column('fechaCompra', sa.DateTime(), nullable=True),
    sa.Column('idEmpleado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idEmpleado'], ['empleado.idEmpleado'], ),
    sa.ForeignKeyConstraint(['idEmpresa'], ['empresa.nit'], ),
    sa.PrimaryKeyConstraint('idCompra')
    )
    op.create_table('detalle_compra',
    sa.Column('idDetalle', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('idCliente', sa.Integer(), nullable=True),
    sa.Column('idCompra', sa.Integer(), nullable=True),
    sa.Column('gramos', sa.Float(), nullable=True),
    sa.Column('foto', sa.String(length=255), nullable=True),
    sa.Column('huella', sa.String(length=255), nullable=True),
    sa.Column('estadoCedula', sa.String(length=255), nullable=True),
    sa.Column('rut', sa.String(length=255), nullable=True),
    sa.Column('antecedentesJuidiciales', sa.String(length=255), nullable=True),
    sa.Column('procuraduria', sa.String(length=255), nullable=True),
    sa.Column('contraloria', sa.String(length=255), nullable=True),
    sa.Column('ofac', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['idCliente'], ['cliente.cedula'], ),
    sa.ForeignKeyConstraint(['idCompra'], ['compra.idCompra'], ),
    sa.PrimaryKeyConstraint('idDetalle')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('detalle_compra')
    op.drop_table('compra')
    op.drop_table('empresa')
    op.drop_table('empleado')
    op.drop_table('cliente')
    # ### end Alembic commands ###
